---
# tasks file for ansible-shell-mac

- name: Ensure zsh-autosuggestions is installed
  homebrew:
    name: "{{ item }}"
    state: installed
  loop:
    - zsh-autosuggestions
    - zsh-completions
    - zsh-syntax-highlighting

- name: enable zsh-autosuggestions
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    marker: "# {mark} - enable zsh-autosuggestions - ANSIBLE MANAGED BLOCK"
    create: yes
    owner: "{{ ansible_env.USER }}"
    mode: 0600
    block: |
      source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

- name: enable zsh-completions
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    marker: "# {mark} - enable zsh-completions - ANSIBLE MANAGED BLOCK"
    create: yes
    owner: "{{ ansible_env.USER }}"
    mode: 0600
    block: |
      autoload -Uz compinit
      compinit

- name: enable zsh-syntax-highlighting
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    marker: "# {mark} - enable zsh-syntax-highlighting - ANSIBLE MANAGED BLOCK"
    create: yes
    owner: "{{ ansible_env.USER }}"
    mode: 0600
    block: |
      source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
