---
# tasks file for ansible-shell-mac

- name: Ensure zsh-autosuggestions is installed
  homebrew:
    name: "{{ item }}"
    state: installed
  loop:
    - zsh-autosuggestions
    - zsh-completions

- name: enable zsh-autosuggestions
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    create: yes
    owner: "{{ ansible_env.USER }}"
    mode: 0600
    line: source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh  blockinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    marker: "# {mark} - enable zsh-completions - ANSIBLE MANAGED BLOCK"
    create: yes
    owner: "{{ ansible_env.USER }}"
    mode: 0600
    block: |
      if type brew &>/dev/null; then
        FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

        autoload -Uz compinit
        compinit
      fi      
