---
# tasks file for ansible-shell-mac

- name: Ensure zsh dependencies are installed
  homebrew:
    name: "{{ item }}"
    state: installed
  loop:
    - zsh-autosuggestions
    - zsh-completions
    - zsh-syntax-highlighting

- name: .zshrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/ansible-shell-mac/files/.zshrc"
    path: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    owner: "{{ ansible_env.USER }}"
    mode: 0644
