---
# tasks file for ansible-shell-mac

- name: Ensure zsh-autosuggestions is installed
  homebrew:
    name: "{{ item }}"
    state: installed
  loop:
    - zsh-autosuggestions

- name: enable zsh-autosuggestions
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    create: yes
    owner: "{{ ansible_env.USER }}"
    mode: 0600
    line: source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh