---
# tasks file for ansible-shell-mac

- name: Ensure zsh dependencies are installed
  homebrew:
    name: "{{ item }}"
    state: installed
  loop:
    - zsh-autosuggestions
    - zsh-completions
    - zsh-syntax-highlighting

- name: ~/.zshrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "# {mark} ~/.zshrc - ANSIBLE MANAGED BLOCK"
    create: yes
    owner: "{{ ansible_env.USER }}"
    mode: 0644
    block: |
      # Set architecture-specific brew share path.
      arch_name="$(uname -m)"
      if [ "${arch_name}" = "x86_64" ]; then
          share_path="/usr/local/share"
      elif [ "${arch_name}" = "arm64" ]; then
          share_path="/opt/homebrew/share"
      else
          echo "Unknown architecture: ${arch_name}"
      fi

      # set promt
      export PS1=% PROMPT='%n @ %~ %# '

      # custom greeting
      echo Welcome back $(whoami)!
      echo Uptime: $(uptime)
      echo IP: $(ifconfig | grep "inet " | grep -v 127.0.0.1 | cut -d\  -f2)

      # Tell homebrew to not autoupdate every single time I run it (just once a week).
      export HOMEBREW_AUTO_UPDATE_SECS=604800

      # enable dircolors
      export CLICOLOR=1

      # enable zsh-autosuggestions
      source ${share_path}/zsh-autosuggestions/zsh-autosuggestions.zsh

      # enable zsh-syntax-highlighting
      source ${share_path}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

      # enable zsh-completions
      autoload -Uz compinit && compinit
