# https://alacritty.org/config-alacritty.html

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[keyboard]
bindings = [
    # use control + tab to switch between tabs
    { key = "Tab", mods = "Control", action = "SelectNextTab" },
    { key = "Tab", mods = "Control | Shift", action = "SelectPreviousTab" },
    { key = "Left", mods = "Alt", chars = "\u001bB" },                       # Skip word left
    { key = "Right", mods = "Alt", chars = "\u001bF" },                      # Skip word right
    { key = "Left", mods = "Command", chars = "\u001bOH" },                  # Jump to beginning of line
    { key = "Right", mods = "Command", chars = "\u001bOF" },                 # Jump to end of line
    { key = "Back", mods = "Command", chars = "\u0015" },                    # Delete line
]
