# https://alacritty.org/config-alacritty.html

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[keyboard]
bindings = [
    # use control + tab to switch between tabs
    { key = "Tab", mods = "Control", action = "SelectNextTab" },
    { key = "Tab", mods = "Control | Shift", action = "SelectPreviousTab" },
]
